name: Run script and upload file

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 8 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Run Python script
        run: python main.py

      - name: Upload output file
        uses: actions/upload-artifact@v3
        with:
          name: output-file
          path: chrome_data.json

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Automated update"
          add: '*.json'

      - name: Rename file
        run: mv chrome_data.json latestChromeData.json

      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PRIVATE_KEY }}
          port: 22
          source: "latestChromeData.json"
          target: ${{ secrets.SERVER_DEPLOY }}/
